
VEHICLE:
  DRIVE_LOOP_HZ : 20
  MAX_LOOPS : 100000

CAMERA:
  CAMERA_RESOLUTION : 
    HEIGHT:          256
    WIDTH:           144
  CAMERA_FRAMERATE : 20

STEERING:
  STEERING_CHANNEL :   0
  STEERING_LEFT_PWM :  480
  STEERING_RIGHT_PWM : 280

THROTTLE:
  THROTTLE_CHANNEL :    1
  THROTTLE_FORWARD_PWM : 420
  THROTTLE_STOPPED_PWM : 370
  THROTTLE_REVERSE_PWM : 300

JOYSTICK:
  USE_JOYSTICK_AS_DEFAULT : False
  JOYSTICK_MAX_THROTTLE :   0.5
  JOYSTICK_STEERING_SCALE : 1.0
  AUTO_RECORD_ON_THROTTLE : False

Nets: "CNN"
    
CNN:
  CNN_IMG_WIDTH : 256
  CNN_IMG_HEIGHT: 144

TRAINING:
  BATCH_SIZE : 128
  TRAIN_TEST_SPLIT : 0.9
